services:
  postgre:
    image: postgres:16-alpine
    restart: always
    # ports:
    #   - "127.0.0.1:5432:5432"  # Opens port 5432 to the host machine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: forum
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d forum"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: always
    environment:
      # Note: Hostname is now 'postgre' instead of 'localhost'
      - DATABASE_URL=postgresql+asyncpg://postgres:password@postgre:5432/forum
      - SECRET_KEY=changeme
      - SESSION_COOKIE_NAME=sakinfan_session
      - SESSION_TTL_SECONDS=604800
      - DEBUG=False
    volumes:
      - .:/app # Mounts local code for easy updates without rebuilding
    depends_on:
      postgre:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/app/app/static:ro # Allows NGINX to read the static files

volumes:
  postgres_data:
