import asyncio
import re
import random
import string
import httpx
import asyncpg
import time
import os
from pathlib import Path
from dotenv import load_dotenv

# Load .env from the project root
env_path = Path(__file__).resolve().parent.parent / ".env"
load_dotenv(dotenv_path=env_path)

BASE_URL = os.getenv("BASE_URL", "http://127.0.0.1:8000")
DB_URL = os.getenv("DATABASE_URL", "postgresql://postgres:password@localhost:5432/forum").replace("+asyncpg", "")

# --- CONFIGURATION ---
USER_COUNT = 50
THREAD_COUNT = 500
POST_COUNT = 10000
CONCURRENCY_LIMIT = 50 # Prevents overloading the server/database connections

def rand_str(length=10):
    return ''.join(random.choices(string.ascii_letters + " ", k=length)).strip()

async def get_csrf(client, url):
    res = await client.get(url)
    match = re.search(r'name="csrftoken"\s+value="([^"]+)"', res.text)
    return match.group(1) if match else None

async def create_thread_task(sem, client, b_id):
    async with sem:
        csrf = await get_csrf(client, f"/board/{b_id}/new")
        if not csrf: return None
        res = await client.post(f"/board/{b_id}/new", data={
            "title": f"Test Thread {rand_str(15)}",
            "body": f"Initial thread content generated by test script: {rand_str(50)}",
            "csrftoken": csrf
        })
        loc = res.headers.get("location")
        return loc.split("/")[-1] if loc and "/thread/" in loc else None

async def create_post_task(sem, client, t_id):
    async with sem:
        csrf = await get_csrf(client, f"/thread/{t_id}")
        if not csrf: return
        await client.post(f"/thread/{t_id}/reply", data={
            "body": f"Simulated user reply: {rand_str(random.randint(20, 100))}",
            "csrftoken": csrf
        })

async def main():
    sem = asyncio.Semaphore(CONCURRENCY_LIMIT)
    
    print("1/6: Seeding 5 specific test boards...")
    conn = await asyncpg.connect(DB_URL)
    board_ids = []
    for i in range(1, 6):
        board_name = f"Test Board {i}"
        await conn.execute(
            """
            INSERT INTO boards (name, description, display_order) 
            VALUES ($1, $2, $3) 
            ON CONFLICT (name) DO NOTHING
            """,
            board_name, f"Automatically generated test board {i}", 10 + i
        )
        row = await conn.fetchrow("SELECT id FROM boards WHERE name = $1", board_name)
        if row:
            board_ids.append(row['id'])
    await conn.close()

    if not board_ids:
        print("Failed to create or fetch test boards.")
        return

    print(f"2/6: Registering {USER_COUNT} users...")
    user_clients = []
    for i in range(USER_COUNT):
        client = httpx.AsyncClient(base_url=BASE_URL, follow_redirects=False, timeout=10.0)
        csrf = await get_csrf(client, "/register")
        if csrf:
            await client.post("/register", data={
                "username": f"tester_{i}_{int(time.time())}",
                "email": f"tester{i}_{int(time.time())}@example.com",
                "password": "password",
                "csrftoken": csrf
            })
        user_clients.append(client)

    print("3/6: Logging in Admin account...")
    admin_client = httpx.AsyncClient(base_url=BASE_URL, follow_redirects=False, timeout=10.0)
    csrf = await get_csrf(admin_client, "/login")
    await admin_client.post("/login", data={
        "username": "admin",
        "password": "changeme",
        "csrftoken": csrf
    })

    print(f"4/6: Creating {THREAD_COUNT} threads concurrently...")
    tasks = [
        create_thread_task(sem, random.choice(user_clients), random.choice(board_ids)) 
        for _ in range(THREAD_COUNT)
    ]
    results = await asyncio.gather(*tasks)
    thread_ids = [tid for tid in results if tid]

    if not thread_ids:
        print("Failed to extract thread IDs. Check application routing.")
        return

    print(f"5/6: Creating {POST_COUNT} posts concurrently...")
    tasks = [
        create_post_task(sem, random.choice(user_clients), random.choice(thread_ids))
        for _ in range(POST_COUNT)
    ]
    # Process in chunks to give feedback and not run out of memory entirely
    chunk_size = 1000
    for i in range(0, len(tasks), chunk_size):
        await asyncio.gather(*tasks[i:i+chunk_size])
        print(f"  ... {min(i + chunk_size, POST_COUNT)}/{POST_COUNT} posts created")

    print("6/6: Executing random deletions, locks, and pins as Admin...")
    for _ in range(15):
        t_id = random.choice(thread_ids)
        
        csrf = await get_csrf(admin_client, f"/thread/{t_id}")
        if csrf:
            await admin_client.post(f"/thread/{t_id}/pin", data={"csrftoken": csrf})
            await admin_client.post(f"/thread/{t_id}/lock", data={"csrftoken": csrf})

        res = await admin_client.get(f"/thread/{t_id}")
        post_ids = re.findall(r'action="/post/([^/]+)/delete"', res.text)
        if post_ids:
            p_id = random.choice(post_ids)
            csrf = await get_csrf(admin_client, f"/thread/{t_id}")
            if csrf:
                await admin_client.post(f"/post/{p_id}/delete", data={"csrftoken": csrf})

    for c in user_clients:
        await c.aclose()
    await admin_client.aclose()

    print("Success: Test execution complete. Application is populated.")

if __name__ == "__main__":
    asyncio.run(main())