events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    # define rate limiting zones based on client IP
    limit_req_zone $binary_remote_addr zone=limit_per_second:10m rate=10r/s;
    limit_req_zone $binary_remote_addr zone=limit_per_minute:10m rate=100r/m;

    upstream web_app {
        server web:8000;
    }

    server {
        listen 80;
        server_name localhost;

        # serve static files directly without hitting FastAPI (omitted from rate limits)
        location /static/ {
            alias /app/app/static/;
            expires 30d;
            add_header Cache-Control "public, max-age=2592000";
        }

        # reverse proxy all other traffic to FastAPI
        location / {
            # apply rate limits
            limit_req zone=limit_per_second burst=20 nodelay;
            limit_req zone=limit_per_minute burst=50 nodelay;
            
            # Return HTTP 429 Too Many Requests instead of default 503
            limit_req_status 429;

            proxy_pass http://web_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}